executable = /afs/cern.ch/work/d/dannc/public/emu_reconstruction/beam/condor_ab0.sh
arguments = $(RUN) $(BRICKID) $(PLATENUMBER)
output = /afs/cern.ch/work/d/dannc/public/emu_reconstruction/logs/output/ab0.$(ClusterId).$(PLATENUMBER).out
error = /afs/cern.ch/work/d/dannc/public/emu_reconstruction/logs/error/ab0.$(ClusterId).$(PLATENUMBER).err
log = /afs/cern.ch/work/d/dannc/public/emu_reconstruction/logs/log/ab0.$(ClusterId).log
+JobFlavour = "tomorrow"
request_memory = 64GB
notification = Never
requirements = (OpSysAndVer =?= "AlmaLinux9")
requirements = Machine =!= LastRemoteHost
on_exit_remove          = (ExitBySignal == False) && ((ExitCode == 1) || (ExitCode == 0))
max_retries             = 3
queue PLATENUMBER in (34)
